CREATE DATABASE IF NOT EXISTS offersell;
USE offersell;

CREATE TABLE IF NOT EXISTS usuarios (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre   VARCHAR(80)  NOT NULL,
  contacto VARCHAR(20),
  correo   VARCHAR(120) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
